# Generated by Django 6.0.2 on 2026-02-05 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='biography/')),
            ],
            options={
                'verbose_name': 'Biografiya',
                'verbose_name_plural': 'Biografiyalar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='books/covers/')),
                ('pdf_file', models.FileField(upload_to='books/pdfs/')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='NewsBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news_blog/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yangiliklar va Blog',
                'verbose_name_plural': 'Yangiliklar va Bloglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('student_info', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='author/')),
            ],
            options={
                'verbose_name': 'Loyiha Muallifi',
                'verbose_name_plural': 'Loyiha Mualliflari',
            },
        ),
        migrations.CreateModel(
            name='ScientificArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_source', models.CharField(max_length=255, verbose_name='Nashr manbasi')),
                ('published_date', models.DateField(verbose_name='Nashr sanasi')),
                ('file', models.FileField(blank=True, help_text='PDF faylni yuklang', null=True, upload_to='scientific_articles/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
            options={
                'verbose_name': 'Ilmiy maqola',
                'verbose_name_plural': 'Ilmiy maqolalar',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('embed_code', models.TextField(help_text="YouTube videoning to'liq embed kodini shu yerga tashlang (<iframe>...</iframe>)", verbose_name='Embed Kod')),
                ('description', models.TextField(blank=True, help_text="Video haqida qisqacha ma'lumot (tahminan 10-15 so'z)", null=True, verbose_name='Qisqacha izoh')),
            ],
            options={
                'verbose_name': 'Video Resurs',
                'verbose_name_plural': 'Video Resurslar',
            },
        ),
    ]
